draw_set_font(font_large_hud)
draw_set_alpha(.7)
draw_rectangle_color(0,0,room_width,34,c_black,c_black,c_black,c_black,false)
draw_rectangle_color(0,706,room_width,room_height,c_black,c_black,c_black,c_black,false)
draw_set_alpha(.3)
draw_rectangle_color(0,38,85,57,c_black,c_black,c_black,c_black,false)
draw_rectangle_color(0,60,85,82,c_black,c_black,c_black,c_black,false)
draw_set_alpha(1)